### ISSUE TITLE
metrics_svr.py 

### ISSUE THREAD

**Issue by Yxs-160** [edoRemelli/MeshSDF#7] opened 2022-01-04 11:23 UTC
good work！However when i ran the metrics_svr.py, i met some problem about nc, anyone can help me?
~/MeshSDF-main$ python metrics_svr.py -e experiments/cars_svr/
Recapping metrics from experiment description: 
This experiment learns a shape representation for cars  using data from ShapeNet version 1.
There are 113 scenes
Stats:
Raw CHD 0.30684
Refined CHD 0.30673
Improvement in CHD 0.04 %
Raw NC nan %
Refined NC nan %
Improvement in NC nan %

**Comment by bguillard** [comment] 2022-01-04 13:47
Hello!
I now have this issue as well. I don't know why we did not notice it previously, perhaps newer versions of pyTorch3D implement cameras differently?

From what I understand, there seems to be an issue with how cameras are computed in 
https://github.com/cvlab-epfl/MeshSDF/blob/6d34bd73839fea29c7f45756b2d43c40fb84cf2f/reconstruct_svr.py#L127
My fix is to replace this line with:
```python
cameras = PerspectiveCameras(device=device, focal_length=-K_cuda[:,0,0] / K_cuda[:,0,2], image_size=((IMG_SIZE, IMG_SIZE),), R=R_cuda, T=t_cuda)
```

You might want to re-run ```reconstruct_svr.py```, since the binary silhouettes used for optimization were likely off as well.
Let me know if the above fix works for you!

**Comment by Yxs-160** [comment] 2022-01-04 15:30
> y fix is to replace this line with:
> ```python
> cameras = Perspective
> ```

thank you for your reply! I have tried  your suggestion. It works! Great！！！

**Comment by Yxs-160** [comment] 2022-01-04 15:31
> Hello! I now have this issue as well. I don't know why we did not notice it previously, perhaps newer versions of pyTorch3D implement cameras differently?
> 
> From what I understand, there seems to be an issue with how cameras are computed in
> 
> https://github.com/cvlab-epfl/MeshSDF/blob/6d34bd73839fea29c7f45756b2d43c40fb84cf2f/reconstruct_svr.py#L127
> 
> 
> My fix is to replace this line with:
> ```python
> cameras = PerspectiveCameras(device=device, focal_length=-K_cuda[:,0,0] / K_cuda[:,0,2], image_size=((IMG_SIZE, IMG_SIZE),), R=R_cuda, T=t_cuda)
> ```
> 
> You might want to re-run `reconstruct_svr.py`, since the binary silhouettes used for optimization were likely off as well. Let me know if the above fix works for you!

thank you for your reply! I have tried your suggestion. It works! Great！！！

**Comment by bguillard** [comment] 2022-01-04 16:54
Alright, thanks for confirming it now works, I have updated the repo with the fix. Closing the issue.

**Closed as completed by bguillard** 2022-01-04 16:54 UTC

**Comment by Sentient07** [comment] 2023-01-17 01:05
Hello,

I'm facing an issue after this change. The input image and rendered aren't from same camera anymore. I'm unable to figure out how/where to fix. @bguillard do you also observe this?

Figure, input, predicted
![input](https://user-images.githubusercontent.com/6195312/212787807-981bed1b-b2d0-4fe5-ac99-5c6b58c02b71.png)
![predicted](https://user-images.githubusercontent.com/6195312/212787810-47b482d8-d35d-46a6-a869-f246210bac5b.png)

**Comment by bguillard** [comment] 2023-01-17 09:46
Hello,
I cannot reproduce the issue: input/predicted normals are aligned on my side, with pytorch3d 0.6.1.
![input](https://user-images.githubusercontent.com/23718226/212864326-7706c31b-d491-4bf8-bfb7-71aec0ac4bb8.png)
![predicted](https://user-images.githubusercontent.com/23718226/212864333-69b14faa-1c01-4883-9b12-e066b41e77a6.png)

**Comment by Sentient07** [comment] 2023-01-17 09:49
Hi,

Thanks for your very quick response. Just to be sure, you're using the rendered images and `rendering_metadata.txt` from here: https://github.com/laughtervv/DISN#download-2d-image-following-3dr2n2httpsgithubcomchrischoy3d-r2n2-please-cite-their-paper-if-you-use-this-image-tar-file ?
